all:
	$(MAKE) -C programme_info-tronc-commun
	$(MAKE) -C programme_mp-option-info
	$(MAKE) -C programme_mpi

clean:
	$(MAKE) clean -C programme_info-tronc-commun
	$(MAKE) clean -C programme_mp-option-info
	$(MAKE) clean -C programme_mpi
