req_Q1='SELECT CLI_NOM,CLI_PRENOM FROM T_CLIENT WHERE TIT_CODE="Mme."'

res_Q2='SELECT CLI_NOM as Nom,CLI_PRENOM as Prénom FROM T_CLIENT WHERE TIT_CODE="M." ORDER BY CLI_NOM,CLI_PRENOM'

res_Q3='SELECT * FROM(SELECT CLI_NOM,COUNT(CLI_NOM) AS ct FROM T_CLIENT GROUP BY CLI_NOM ORDER BY CLI_NOM) WHERE ct>1'

res_Q4='SELECT FAC_ID FROM T_LIGNE_FACTURE WHERE LIF_REMISE_MONTANT IS NULL and LIF_REMISE_POURCENT IS NULL'

res_Q5='SELECT DISTINCT CLI_ID FROM T_FACTURE JOIN T_LIGNE_FACTURE ON T_FACTURE.FAC_ID=T_LIGNE_FACTURE.FAC_ID WHERE LIF_REMISE_MONTANT IS NULL and LIF_REMISE_POURCENT  IS NULL'

res_Q6='SELECT CLI_NOM,CLI_PRENOM FROM T_CLIENT JOIN (SELECT DISTINCT CLI_ID FROM T_FACTURE JOIN T_LIGNE_FACTURE ON T_FACTURE.FAC_ID=T_LIGNE_FACTURE.FAC_ID WHERE LIF_REMISE_MONTANT IS NULL and LIF_REMISE_POURCENT  IS NULL) AS T ON T_CLIENT.CLI_ID=T.CLI_ID'

res_Q7="""SELECT COUNT(CHB_ID) FROM TJ_CHB_PLN_CLI WHERE PLN_JOUR='2001-01-28' AND CHB_PLN_CLI_RESERVE=0 AND CHB_PLN_CLI_OCCUPE=1"""

res_Q8='SELECT CLI_NOM, CLI_PRENOM, TEL_NUMERO FROM T_CLIENT JOIN T_TELEPHONE ON T_CLIENT.CLI_ID = T_TELEPHONE.CLI_ID"

res_Q9='SELECT CHB_ETAGE,COUNT(CHB_NUMERO) FROM T_CHAMBRE GROUP BY CHB_ETAGE'

res_Q10="""SELECT CHB_ETAGE,COUNT(CHB_NUMERO) FROM T_CHAMBRE JOIN TJ_CHB_PLN_CLI ON T_CHAMBRE.CHB_ID=TJ_CHB_PLN_CLI.CHB_ID WHERE PLN_JOUR='2001-01-28' AND CHB_PLN_CLI_OCCUPE=1 GROUP BY CHB_ETAGE"""

# Q11 Dur dur...
res_Q11 = """SELECT CHBNB_T - NB_OCC as nb, CHB_ETAGE FROM (SELECT COUNT(*) AS CHBNB_T, CHB_ETAGE FROM T_CHAMBRE GROUP BY CHB_ETAGE) NATURAL JOIN (SELECT count(*) as NB_OCC, CHB_ETAGE FROM T_CHAMBRE NATURAL JOIN TJ_CHB_PLN_CLI WHERE CHB_PLN_CLI_OCCUPE=1 and PLN_JOUR="2001-01-28" GROUP BY CHB_ETAGE) GROUP BY CHB_ETAGE"""

res_Q12="""SELECT SUM(CHB_PLN_CLI_NB_PERS) FROM T_CHAMBRE C JOIN TJ_CHB_PLN_CLI P ON C.CHB_ID = P.CHB_ID WHERE PLN_JOUR BETWEEN '2000-01-01' AND '2000-12-31'"""