/*Q1*/

SELECT CLI_NOM, CLI_PRENOM, TIT_CODE FROM T_CLIENT ;

/*Q2*/

SELECT COUNT(*) FROM T_CLIENT ;

/*Q3*/

SELECT CLI_NOM, CLI_PRENOM, TIT_CODE FROM T_CLIENT WHERE TIT_CODE='Mme.';


/*Q4*/

SELECT CLI_NOM, CLI_PRENOM, TIT_CODE FROM T_CLIENT WHERE TIT_CODE='Mme.' OR TIT_CODE='Melle.' ;

/*Q5*/

SELECT count(*) FROM T_CLIENT WHERE TIT_CODE='Mme.' OR TIT_CODE='Melle.' ;

/*Q6*/

SELECT CLI_NOM as noms, CLI_PRENOM as prenoms FROM T_CLIENT WHERE TIT_CODE='Mme.' OR TIT_CODE='Melle.' ORDER BY noms, prenoms ;

/*Q7*/

SELECT T_CLIENT.CLI_NOM, T_TELEPHONE.TEL_NUMERO FROM T_CLIENT JOIN T_TELEPHONE ON T_CLIENT.CLI_ID=T_TELEPHONE.CLI_ID;

/*Q8*/
SELECT NOM FROM
 (SELECT CLI_NOM as Nom, CLI_PRENOM as prenom, COUNT(*) as nb_nom FROM T_CLIENT GROUP BY Nom)
 WHERE nb_nom>1;

/*Q9*/


SELECT * FROM(SELECT CLI_NOM,COUNT(CLI_NOM) AS ct
 FROM T_CLIENT GROUP BY CLI_NOM ORDER BY CLI_NOM) WHERE ct>1;

 
 /*Q10*/
 
 SELECT AVG(LIF_REMISE_MONTANT),  AVG(LIF_REMISE_POURCENT) FROM T_LIGNE_FACTURE;

  /*Q11*/
 
 SELECT MAX(LIF_REMISE_MONTANT),  MAX(LIF_REMISE_POURCENT) FROM T_LIGNE_FACTURE;

 /*Q12*/
SELECT FAC_ID as facid1 FROM T_LIGNE_FACTURE 
WHERE LIF_REMISE_POURCENT>0 OR LIF_REMISE_MONTANT>0;




/*Q13*/
SELECT DISTINCT CLI_ID FROM T_FACTURE
JOIN
(SELECT T_LIGNE_FACTURE.FAC_ID as facid1  FROM T_LIGNE_FACTURE 
WHERE LIF_REMISE_POURCENT>0 OR LIF_REMISE_MONTANT>0) 
ON facid1=T_FACTURE.FAC_ID;


/*Q14*/

SELECT CLI_ID FROM T_CLIENT
EXCEPT
SELECT DISTINCT CLI_ID FROM T_FACTURE
JOIN
(SELECT T_LIGNE_FACTURE.FAC_ID as facid1  FROM T_LIGNE_FACTURE 
WHERE LIF_REMISE_POURCENT>0 OR LIF_REMISE_MONTANT>0) 
ON facid1=T_FACTURE.FAC_ID;

/*Q15*/
SELECT T_CLIENT.CLI_NOM, T_CLIENT.CLI_PRENOM, max(montant_total) FROM T_CLIENT
JOIN
(SELECT CLI_ID as id_client, sum(montant) as montant_total FROM T_FACTURE
JOIN
(SELECT T_LIGNE_FACTURE.FAC_ID as facid1,  T_LIGNE_FACTURE.LIF_REMISE_MONTANT as montant FROM T_LIGNE_FACTURE 
WHERE LIF_REMISE_POURCENT>0 OR LIF_REMISE_MONTANT>0) 
ON facid1=T_FACTURE.FAC_ID GROUP BY CLI_ID)
ON
T_CLIENT.CLI_ID=id_client;



/*Q15*/
SELECT COUNT(*) FROM
(SELECT CLI_ID, CLI_NOM, CLI_PRENOM FROM T_CLIENT
EXCEPT
SELECT DISTINCT CLI_ID FROM T_FACTURE
JOIN
(SELECT T_LIGNE_FACTURE.FAC_ID as facid1  FROM T_LIGNE_FACTURE 
WHERE LIF_REMISE_POURCENT>0 OR LIF_REMISE_MONTANT>0) 
ON facid1=T_FACTURE.FAC_ID);

/*************************/
/*Q10*/
SELECT  DISTINCT T_FACTURE.CLI_ID FROM T_FACTURE JOIN
(SELECT T_LIGNE_FACTURE.FAC_ID as id1 FROM T_LIGNE_FACTURE EXCEPT SELECT FAC_ID FROM T_LIGNE_FACTURE 
WHERE LIF_REMISE_POURCENT>0 OR LIF_REMISE_MONTANT>0)
ON id1=T_FACTURE.FAC_ID;

/*Q11*/
SELECT T_CLIENT.CLI_NOM, T_CLIENT.CLI_PRENOM FROM T_CLIENT JOIN 
(SELECT  DISTINCT T_FACTURE.CLI_ID as client_id FROM T_FACTURE JOIN
(SELECT T_LIGNE_FACTURE.FAC_ID as id1 FROM T_LIGNE_FACTURE EXCEPT SELECT FAC_ID FROM T_LIGNE_FACTURE 
WHERE LIF_REMISE_POURCENT>0 OR LIF_REMISE_MONTANT>0)
ON id1=T_FACTURE.FAC_ID)
ON T_CLIENT.CLI_ID=client_id;

SELECT CLI_NOM,CLI_PRENOM FROM T_CLIENT JOIN (SELECT DISTINCT CLI_ID FROM T_FACTURE JOIN T_LIGNE_FACTURE ON T_FACTURE.FAC_ID=T_LIGNE_FACTURE.FAC_ID WHERE LIF_REMISE_MONTANT IS NULL and LIF_REMISE_POURCENT  IS NULL) AS T ON T_CLIENT.CLI_ID=T.CLI_ID

/*
SELECT CLI_NOM,CLI_PRENOM FROM T_CLIENT JOIN (SELECT DISTINCT CLI_ID FROM T_FACTURE JOIN T_LIGNE_FACTURE ON T_FACTURE.FAC_ID=T_LIGNE_FACTURE.FAC_ID WHERE LIF_REMISE_MONTANT IS NULL and LIF_REMISE_POURCENT  IS NULL) AS T ON T_CLIENT.CLI_ID=T.CLI_ID
*/


/*Q7*/
SELECT COUNT(*) FROM (SELECT TJ_CHB_PLN_CLI.PLN_JOUR, TJ_CHB_PLN_CLI.CHB_PLN_CLI_OCCUPE,
TJ_CHB_PLN_CLI.CHB_PLN_CLI_RESERVE
 FROM TJ_CHB_PLN_CLI
 WHERE TJ_CHB_PLN_CLI.PLN_JOUR='2001-01-28' AND CHB_PLN_CLI_RESERVE=0);
 
 

  /*Q9*/
 
 SELECT CHB_ETAGE, count(*) FROM T_CHAMBRE GROUP BY CHB_ETAGE;
 
 
   /*Q10*/
 
 SELECT T_CHAMBRE.CHB_ETAGE, count(*) FROM T_CHAMBRE  JOIN TJ_CHB_PLN_CLI
 ON TJ_CHB_PLN_CLI.CHB_ID=T_CHAMBRE.CHB_ID  WHERE TJ_CHB_PLN_CLI.PLN_JOUR="2001-01-28"
 GROUP BY T_CHAMBRE.CHB_ETAGE;
 
    /*Q11*/
 SELECT etage1, nbetage1-nbetage2 FROM 
 (SELECT CHB_ETAGE as etage1, count(*) as nbetage1 FROM T_CHAMBRE GROUP BY CHB_ETAGE)
 JOIN 
(SELECT T_CHAMBRE.CHB_ETAGE as etage2, count(*) as nbetage2 FROM T_CHAMBRE  JOIN TJ_CHB_PLN_CLI
 ON TJ_CHB_PLN_CLI.CHB_ID=T_CHAMBRE.CHB_ID  WHERE TJ_CHB_PLN_CLI.PLN_JOUR="2001-01-28"
 GROUP BY T_CHAMBRE.CHB_ETAGE)
 on etage1=etage2;
